    </div>

</div>

<style>

     .bridge .buttons {
         width: 100%;
         text-align: center;
     }

    .bridge .buttons form button {
        padding: 5px;
        background-color: red;
    }

    .buttons p {
        margin: 0;
    }

    .bridge {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .bridge .container {
        width: 600px;
    }

     .bridge .container .content-in {
         padding: 15px;
     }

    .bridge .container .content {
        width:100%;
        background: white;
        border-radius: 10px;
    }

    .bridge .connector-error-messages {

    }

    .bridge .form {
        display: flex;
        flex-direction: column;
        text-align: left;
    }

    .bridge .btn {
        background-color: #4CAF50;
        border: none;
        color: white;
        padding: 10px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        margin: 10px 2px;
        cursor: pointer;
        border-radius: 10px;
    }

     .bridge .connector-success-messages-in {
         display: flex;
         justify-content: center;
         padding: 10px;
     }

     .bridge .connector-error-messages-in {
         display: flex;
         justify-content: center;
         padding: 10px;
     }

     .bridge .sign {
         margin:0 10px;
         display: inline-block;
         width: 15px;
         height: 15px;
         border-radius: 50%;
         background-color: lightgray;
         text-align: center;
         line-height: 15px;
         font-weight: bold;
     }

     .bridge .connector-error-messages .sign {
         background-color: #f6a19e;
         color:#8e1f0b;
     }

     p {
         padding:0;
         margin:0;
     }

     .bridge .connector-success-messages {
         align-items: center;
         margin-bottom: 20px;
         width:100%;
         background: #ebf4ff;
         color: #2d658b;
     }

     .bridge .connector-error-messages {
         align-items: center;
         margin-bottom: 20px;
         width:100%;
         background: #fec3c1;
         border: 1px solid #8e1f0b;
         color: #8e1f0b;
     }

     .bridge input:not([type="checkbox"]) {
         width:270px;
     }

     .bridge .flex {
            display: flex;
            justify-content: space-between;
         padding-bottom: 20px;
     }

     .bridge .text-left {
            text-align: left;
     }

     .bridge .text-right {
         text-align: right;
     }
</style>
